[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/api/solve"
  to = "/.netlify/functions/solve"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Methods" = "POST, OPTIONS", "Access-Control-Allow-Headers" = "Content-Type" }